# MAIN base
baseURL = "https://xkld.pages.dev/"
languageCode = "vi-VN"
title = "VietNam Peace | Công ty xuất khẩu lao động Nhật Bản uy tín"
theme = "vnhb"
removePathAccents = true


# Navigation Bar
[[menu.main]]
    name = "Trang Chủ"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "Giới Thiệu"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Hỏi Đáp"
    url = "#faq"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Trang Chủ"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Bài Viết Mới Nhất"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Privacy & Policy"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Liên Hệ"
    url = "/contact"
    weight = 4

[taxonomies]
  category = 'categories'
  tag = 'tags'

[permalinks]
tags = "/tag/:slug/"

# Footer Address
[params.address]
address = "Lô 41, Bờ Quan 12, Ngũ Hành Sơn, Đà Nẵng"
email = "info.vietnamhoabinh@gmail.com"
phone = "+84 0942.259.111"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/pg/staticmania"
twitter = "https://twitter.com/static_mania"
github = "https://github.com/StaticMania"

[params]

# Header
logo = "images/logo.png"
fabFormURL = "https://fabform.io/f/zWMBVeW"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Cập nhật bản tin mới của VietNam Peace"
copyright1 = "All right reserved"
copyright2 = "Copyright ©  <a href=\"https://jgo.vn/\" target=\"_blank\">Jgo</a> {year}"

#contact
email = "info.vietnamhoabinh@gmail.com"

