# MAIN base
baseURL = "https://xkld.pages.dev/"
languageCode = "vi-VN"
title = "Việt Nam Hòa Bình (VietNam Peace) | Công ty xuất khẩu lao động Nhật Bản uy tín"
removePathAccents = true
enableRobotsTXT = true

# Navigation Bar
[[menu.main]]
    name = "Trang Chủ"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "Giới Thiệu"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Hỏi Đáp"
    url = "#faq"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Trang Chủ"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Bài Viết Mới Nhất"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Chính sách bảo mật"
    url = "/chinh-sach-bao-mat"
    weight = 3
[[menu.sitemap]]
    name = "Liên Hệ"
    url = "/lien-he"
    weight = 4

[taxonomies]
  tag = 'tags'

[permalinks]
tags = "/tag/:slug/"

# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Footer Address
[params.address]
address = "Lô 41, Bờ Quan 12, Ngũ Hành Sơn, Đà Nẵng"
email = "info.vietnamhoabinh@gmail.com"
phone = "+84 0942.259.111"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/pg/jgoxkld"
twitter = "https://twitter.com/jgoxkld"
github = "https://github.com/vietnampeace"

# Footer Address
[params.form]
formID = "1FAIpQLSdtHkRMU85AaZU2KOfuPabl1A56hBxzSriLEP-MZ8SGY_0QkA"
name = "entry.2005620554"
phone = "entry.1045781291"
subject = "entry.1166974658"
noidung = "entry.839337160"

[params]

# Header
logo = "images/logo.svg"
fabFormURL = "https://fabform.io/f/zWMBVeW"
googleAnalytics = "UA-235714187-3"
description = "Công ty Việt Nam Hòa Bình là trung tâm đào tạo nguồn nhân lực xuất khẩu lao động Nhật Bản. Xuất khẩu lao động Nhật Bản, tạo ra cơ hội để đạt được ước mơ của bạn."

# Footer
footerTitle = "Cập nhật bản tin mới của VietNam Peace"
copyright1 = "All right reserved"
copyright2 = "Copyright ©  <a href=\"https://jgo.vn/\" target=\"_blank\">Jgo</a> {year}"

#contact
email = "info.vietnamhoabinh@gmail.com"

## Open Graph
images = ["vietnampeace.png"]
ogLocale = "vi_VN"
domainTLD = "xkld.pages.dev"
titleHome = "VietNam Peace | Công ty xuất khẩu lao động Nhật Bản uy tín"

## Twitter Cards
twitterSite = "@vcr_labs"
twitterCreator = "@daicinema"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Việt Nam Hòa Bình"
schemaAuthor = "VietNamPeace"
schemaAuthorTwitter = "https://twitter.com/daicinema"
schemaAuthorLinkedIn = "www.linkedin.com/in/daicine"
schemaAuthorGitHub = "https://github.com/vietnampeace"
schemaLocale = "vi_VN"
schemaLogo = "vietnampeace-logo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "vietnampeace.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/jgoxkld"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/vietnampeace/vcrlab"
schemaSection = "blog"