
name = "VietNam Peace"
license = "MIT"
licenselink = "https://github.com/xkldnhat/xkld/blob/main/LICENSE"
description = "VietNam Peace - Công ty xuất khẩu lao động nhật bản uy tín tại Việt Nam."
homepage = "https://vietnamhoabinh.com/"
tags = ['văn hóa', 'du lịch', 'xuất khẩu lao động']
features = ['bootstrap 4', 'responsive design', 'blog', 'responsive','landing-page', 'minimal', 'business', 'agency-template', 'hugo-theme', 'portfolio', 'company', 'creative', 'contact-form']
min_version = "0.41.0"

[author]
  name = "Jgo"
  homepage = "https://jgo.vn/"